###### TEMPLATES AND HOW TO ORGANIZE STUFF #####

#### NAMING ---------------------------------------------------------
#### FILE NAMES

### MANUSCRIPT
# MSc_HS_Manuscript_YYYY.MM.DD.Rmd

### SIGNLE SCRIPTS
# import_data.R ---> fixup_data.R ---> analysis_data.R ---> figures_data.R

# all scripts go into their respective _plans
# import_plan.R ---> transformation_plan.R ---> analysis_plan.R ---> figures_plan.R 

# all plans go into combined_plan.R 
# combined_plan.R goes into manuscript_plan (?)


### MARKDOWN CHUNK TEMPLATES ------------------------------

## FIGURE CHUNKS
# ```{r, echo = FALSE, fig.cap = "This is the caption for my figure."}
# #plot_XXX_wng
# ```

## TABLE CHUNKS 
#```{r, echo = FALSE}
## table of model output form best fitted model
#knitr::kable(clean_output.model.XXX[,], 
#format = "markdown",
#caption = "This is my table caption",
#align = "lccrr" # left center center right right is the alignment in the columns
#)
#```

### TABLES ----------------------------------------
## neat table with bold significant rows, except intercept
clean_output.model.agb %>% 
  kable(booktabs = T, 
        caption = "Output from model that performed best, aboveground biomass ~ w * n + g.") %>%
  kable_styling() %>%
  row_spec(which(clean_output.model.agb$p.value < 0.05001 & 
                   clean_output.model.agb$term != "Intercept (no N, no warming, no grazing)"),
           bold = T) 


# ### Nitrogen table
# ```{r, nitrogen-table, echo = FALSE}
# knitr::kable(nitrogen_table[,], 
#              format = "markdown",
#              caption = "caption caption caption.") 
# 
# knitr::kable(data_variable_table[,], 
#              format = "markdown",
#              caption = "caption caption caption.") 
# ```



# MARKDOWN -------------------------------------------------
  
#   # Neat things in markdown
#   
#   
#   # Header 1
#   
#   
#   ## Header 2
#   
#   
#   ### Header 3
# 
# 
# #### Header 4
# 
# 
# ##### Header 5
# 
# 
# ###### Header 6
# 
# 
# 
# * **Bold text** when you wrap text in ** on each side.  
# 
# * *Italic text* when you wrap text in * on each side.  
# 
# * ***Bold and italic text*** when you wrap text in *** on each side.  
# 
# * ~~Strikethough~~ when you wrap text in ~~ on each side.  
# 
# 
# # Code chunk options
# 
# `include = FALSE` prevents code and results from appearing in the finished file. R Markdown still runs the code in the chunk, and the results can be used by other chunks.  
# 
# `echo = FALSE` prevents code, but not the results from appearing in the finished file. This is a useful way to embed figures.  
# 
# `message = FALSE` prevents messages that are generated by code from appearing in the finished file.  
# 
# `warning = FALSE` prevents warnings that are generated by code from appearing in the finished.  
# 
# `fig.cap = "..."` adds a caption to graphical results.  
# 
# 
# 
# # Global options
# 
# To set global options that apply to every chunk in your file, call `knitr::opts_chunk$set` in a code chunk. `Knitr` will treat each option that you pass to `knitr::opts_chunk$set` as a global default that can be overwritten in individual chunk headers.





### FIGURES ---------------------------------------------------------

# SCATTER PLOT
plotname <- ggplot(data = DF, aes(x = , y = )) +
  geom_point(color = "blue", size = 3, alpha = 0.5) +
  labs( # if you put = waiver() it will fill it with default values 
    title = waiver(),
    subtitle = waiver(),
    caption = waiver(),
    tag = waiver(),
    alt = waiver(),
    alt_insight = waiver()
  )

xlab(label)

ylab(label)


### FILTERS
# # only warming 
# filter(grazing == "C") %>% 
# filter(Nlevel == 1 & 2 & 3) %>% 
# 
# # only nitrogen
# filter(warming == "A") %>% 
# filter(grazing == "C") %>% 
# 
# # only grazing 
# filter(warming == "A") %>% 
# filter(Nlevel == "1" & "2" & "3") %>% 
    